import { formatDate } from './dates'
import { useState } from 'react'
import { CalendarClock, ChevronRight, Wrench } from 'lucide-react'
import { nextMaintenance } from './inventoryRules'

type MaintenanceAsset = { id:string; name:string; type:string; brand:string; model:string; owner:string; status:string; acquired:string; maintenance:string; lastMaintenance:string }
export function Maintenance({assets,today,openEquipment}:{assets:MaintenanceAsset[];today:string;openEquipment:(id:string)=>void}){
 const [range,setRange]=useState('Todos')
 function state(asset:MaintenanceAsset){const due=nextMaintenance(asset.maintenance==='Sí'?asset.lastMaintenance:asset.acquired);if(!due)return 'Sin fecha';if(due<today)return 'Vencido';const limit=new Date(`${today}T12:00:00Z`);limit.setDate(limit.getDate()+30);return due<=limit.toISOString().slice(0,10)?'Próximo':'Programado'}
 function days(due:string){return Math.ceil((new Date(`${due}T12:00:00Z`).getTime()-new Date(`${today}T12:00:00Z`).getTime())/86400000)}
 const rows=assets.map(asset=>({...asset,due:nextMaintenance(asset.maintenance==='Sí'?asset.lastMaintenance:asset.acquired)})).filter(asset=>range==='Todos'||state(asset)===range).sort((a,b)=>(a.due||'9999').localeCompare(b.due||'9999'))
 return <section className="panel"><div className="panel-head"><div><h2>Plan de mantenimiento preventivo</h2><p>Periodicidad: cada 6 meses. La fecha se calcula desde el último mantenimiento o, si no existe, desde la adquisición.</p></div><Wrench size={24}/></div><div className="filters"><label>Mostrar<select aria-label="Filtrar mantenimiento" value={range} onChange={e=>setRange(e.target.value)}><option>Todos</option><option>Vencido</option><option>Próximo</option><option>Programado</option><option>Sin fecha</option></select></label></div><div className="maintenance-summary"><article><b>{assets.filter(a=>state(a)==='Vencido').length}</b><span>Vencidos</span></article><article><b>{assets.filter(a=>state(a)==='Próximo').length}</b><span>Próximos 30 días</span></article><article><b>{assets.filter(a=>state(a)==='Programado').length}</b><span>Programados</span></article><article><b>{assets.filter(a=>state(a)==='Sin fecha').length}</b><span>Sin fecha</span></article></div><div className="table-wrap"><table><thead><tr><th>Equipo</th><th>Responsable</th><th>Último mantenimiento</th><th>Próximo mantenimiento</th><th>Estado</th><th></th></tr></thead><tbody>{rows.map(asset=>{const status=state(asset);return <tr key={asset.id}><td><button className="text-button" onClick={()=>openEquipment(asset.id)}>{asset.id} · {asset.name}</button><small>{asset.brand} {asset.model} · {asset.type}</small></td><td>{asset.owner==='Sin asignar'?'Libre':asset.owner}</td><td>{asset.maintenance==='Sí'?formatDate(asset.lastMaintenance)||'Por confirmar':'No registrado'}</td><td>{formatDate(asset.due)||'Por confirmar'}</td><td><span className={`pill ${status==='Vencido'?'bad':status==='Próximo'?'review':status==='Programado'?'good':''}`}><CalendarClock size={12}/>{status}{asset.due&&status!=='Sin fecha'&&<small>{status==='Vencido'?`${Math.abs(days(asset.due))} días de atraso`:`en ${days(asset.due)} días`}</small>}</span></td><td><button className="icon-button" aria-label={`Abrir hoja de vida de ${asset.name}`} onClick={()=>openEquipment(asset.id)}><ChevronRight size={18}/></button></td></tr>})}{!rows.length&&<tr><td colSpan={6}>No hay equipos en este filtro.</td></tr>}</tbody></table></div><p className="table-footer">Desde la ficha del equipo → Hoja de vida puedes registrar “Mantenimiento realizado”; esa fecha actualiza automáticamente este plan.</p></section>
}
