import { useState } from 'react'
import type { Dispatch, FormEvent, SetStateAction } from 'react'
export type PlatformUser={id:string;name:string;email:string;role:string;active:boolean}
export function PlatformUsers({users,setUsers}:{users:PlatformUser[];setUsers:Dispatch<SetStateAction<PlatformUser[]>>}){
 const [editing,setEditing]=useState<PlatformUser|null>(null),[creating,setCreating]=useState(false),[message,setMessage]=useState('')
 function remove(id:string){if(id==='fanor'){setMessage('El administrador principal no se puede eliminar.');return}if(window.confirm('¿Eliminar este usuario de la plataforma?'))setUsers(items=>items.filter(u=>u.id!==id))}
 function save(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const name=String(f.get('name')||'').trim();const email=String(f.get('email')||'').trim().toLowerCase();if(users.some(u=>u.email.toLowerCase()===email&&u.id!==editing?.id)){setMessage('Ya existe un usuario con ese correo.');return}if(!name)return;const user={id:editing?.id||crypto.randomUUID(),name,email,role:editing?.id==='fanor'?'Administrador TI':String(f.get('role')),active:editing?.id==='fanor'?true:f.get('active')==='on'};setUsers(items=>editing?items.map(u=>u.id===editing.id?user:u):[...items,user]);setCreating(false);setEditing(null);setMessage('Configuración guardada en esta sesión de demostración.')}
 return <section className="panel"><div className="panel-head"><div><h2>Usuarios de la plataforma</h2><p>Configura quién podrá editar el inventario y quién solo consultará reportes.</p></div><button className="primary" onClick={()=>{setCreating(true);setEditing(null);setMessage('')}}>Agregar usuario</button></div><p className="demo">Configuración de demostración: no crea accesos reales ni envía invitaciones. Los permisos se aplicarán en el servidor al implementar autenticación.</p>{message&&<p className="notice" role="status">{message}</p>}{creating?<form key={editing?.id||'new'} onSubmit={save}><div className="form-grid"><label>Nombre<input name="name" required maxLength={120} defaultValue={editing?.name||''}/></label><label>Correo de acceso<input name="email" type="email" required maxLength={150} defaultValue={editing?.email||''}/></label><label>Perfil<select name="role" defaultValue={editing?.role||'Solo reportes'} disabled={editing?.id==='fanor'}><option>Administrador TI</option><option>Editor de inventario</option><option>Solo reportes</option></select></label><label>Usuario habilitado<input name="active" type="checkbox" defaultChecked={editing?.active??true} disabled={editing?.id==='fanor'}/></label></div><p>El administrador principal se mantiene activo para conservar el acceso de administración.</p><div className="actions"><button className="secondary" type="button" onClick={()=>{setCreating(false);setEditing(null)}}>Cancelar</button><button className="primary">Guardar usuario de prueba</button></div></form>:<div className="table-wrap"><table><thead><tr><th>Usuario</th><th>Correo</th><th>Permisos</th><th>Estado</th><th></th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td>{u.name}</td><td>{u.email}</td><td>{u.role}</td><td>{u.active?'Habilitado':'Deshabilitado'}</td><td><button className="secondary" onClick={()=>{setCreating(true);setEditing(u);setMessage('')}}>Editar permisos</button><button className="secondary danger-button" onClick={()=>remove(u.id)}>Eliminar</button></td></tr>)}</tbody></table></div>}<h3>Alcance de cada perfil</h3><div className="table-wrap"><table><thead><tr><th>Perfil</th><th>Inventario</th><th>Reportes</th><th>Credenciales y usuarios</th></tr></thead><tbody><tr><td>Administrador TI</td><td>Consultar y editar</td><td>Consultar y exportar</td><td>Administrar</td></tr><tr><td>Editor de inventario</td><td>Consultar y editar equipos, monitores, responsables y licencias</td><td>Consultar y exportar</td><td>Sin acceso</td></tr><tr><td>Solo reportes</td><td>Sin edición</td><td>Solo consultar</td><td>Sin acceso</td></tr></tbody></table></div></section>
}
